public enum Achievements {
    // Jump kills
    JUMPKILL_ONE,
    JUMPKILL_TWO,
    JUMPKILL_THREE,
    JUMPKILL_FOUR,
    // Monastery Boss
    BOSS_MONASTERY_VEZ,
    BOSS_MONASTERY_EZ,
    BOSS_MONASTERY,
    BOSS_MONASTERY_HARD,
    BOSS_MONASTERY_EXTREME,
    // Night Bar boss
    BOSS_NIGHT_BAR_VEZ,
    BOSS_NIGHT_BAR_EZ,
    BOSS_NIGHT_BAR,
    BOSS_NIGHT_BAR_HARD,
    BOSS_NIGHT_BAR_EXTREME,
    // Hospital boss
    BOSS_HOSPITAL_VEZ,
    BOSS_HOSPITAL_EZ,
    BOSS_HOSPITAL,
    BOSS_HOSPITAL_HARD,
    BOSS_HOSPITAL_EXTREME,
    // Desert boss
    BOSS_DESERT_VEZ,
    BOSS_DESERT_EZ,
    BOSS_DESERT,
    BOSS_DESERT_HARD,
    BOSS_DESERT_EXTREME,
    // Lab boss
    BOSS_LAB_VEZ,
    BOSS_LAB_EZ,
    BOSS_LAB,
    BOSS_LAB_HARD,
    BOSS_LAB_EXTREME,
    // HQ boss
    BOSS_COMMIE_HQ_VEZ,
    BOSS_COMMIE_HQ_EZ,
    BOSS_COMMIE_HQ,
    BOSS_COMMIE_HQ_HARD,
    BOSS_COMMIE_HQ_EXTREME,
    // Final boss
    FINAL_BOSS_VEZ,
    FINAL_BOSS_EZ,
    FINAL_BOSS,
    FINAL_BOSS_HARD,
    FINAL_BOSS_EXTREME,
    // Secrets
    SECRET_FOUND,
    SELECT_LEVEL_FOUND,
    PATH_BOMB_OPEN
}
